version: "3.8"

services:
  backend:
    build: ./src/backend
    container_name: backend
    volumes:
      - backend-data:/app/devices.db
    ports:
      - "5000:5000"
    networks:
      - app-net

  frontend:
    build: ./src/frontend
    container_name: frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:5000/devices
    networks:
      - app-net

volumes:
  backend-data:

networks:
  app-net:
    driver: bridge
